Added scala scripts

diff --git a/varsq b/varsq
--- a/varsq
+++ b/varsq
@@ -33,6 +33,8 @@ _help() {
     echo "  env       Show environment variables for the target"
     echo "  mkcert    Generate self-signed SSL certificate and key"
     echo "  resolved  Show resolved environment variables (evaluated values)"
+    echo "  run       Run a python or scala script"
+    echo "  scripts   List available python and scala scripts"
     echo "  start     Start the docker containers"
     echo "  stop      Stop the docker containers"
     echo "  status    Show the status of the docker containers"
@@ -163,6 +165,32 @@ _resolved() {
     echo "------------------------------------------------------"
 }
 
+_run() {
+    if [ ! -f "$ENV_FILE" ]; then
+        echo "Error: $ENV_FILE not found. Run the 'configure' command first." >&2
+        return 1
+    fi
+
+    SCRIPT_NAME=$(basename -- "$1")
+    SCRIPT_EXTENSION="${SCRIPT_NAME##*.}"
+
+    if [ "$SCRIPT_EXTENSION" = "py" ]; then
+        python "$BASE_DIR/etc/python/$1" "${@:2}"
+        exit
+    elif [ "$SCRIPT_EXTENSION" = "sc" ]; then
+        source "$BASE_DIR/bin/docker-env.sh"
+        export VARS_PWD="$VARS_KB_DATABASE_PASSWORD"
+        "$BASE_DIR/bin/scala/$1" "${@:2}"
+        exit
+    fi
+
+}
+
+_scripts() {
+    # TODO list py and sc scripts in etc/python and etc/scala
+    
+}
+
 _start() {
     echo "Starting service using docker compose..."
     echo "    Using environment file at $ENV_FILE"
@@ -245,6 +273,9 @@ case "$SUBCOMMAND" in
         ;;
     resolved)
         _resolved "$@"
+        ;;
+    run)
+        _run "$@"
         ;;
     start)
         _start "$@"
